name: C/C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest}
          - {os: macOS-latest}
          - {os: ubuntu-16.04}

    steps:
      - uses: actions/checkout@v2
      - name: Query dependencies
        run: make
