name: SolarisVM

on: [push]

jobs:
  testsolaris:
    runs-on: macos-latest
    name: A job to run test Solaris
    steps:
    - uses: actions/checkout@v2
    - name: Test in solaris
      id: test
      uses: vmactions/solaris-vm@v0.0.1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: pkgutil -y -i socat
        run: |
          echo "Test Make"
          make
